name: darkness_dungeon
description: "A new Flutter project."

publish_to: "none"

version: 1.5.9+1

environment:
  sdk: ^3.9.2
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bonfire: ^3.15.1
  flame_audio: ^2.10.2
  flame_splash_screen: ^0.3.1
  url_launcher: ^6.3.1
  win32: ^5.10.0

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/emote/
    - assets/images/npc/
    - assets/images/enemy/
    - assets/images/enemy/goblin/
    - assets/images/enemy/imp/
    - assets/images/enemy/mini_boss/
    - assets/images/enemy/boss/
    - assets/images/player/
    - assets/images/items/
    - assets/images/tiled/
    - assets/audio/
    - assets/l10n/

  fonts:
    - family: Normal
      fonts:
        - asset: assets/fonts/font_pixel.ttf
