import 'package:darkness_dungeon/gameplay/inventory/models/item_rarity.dart';

class ConsumableData {
  final String id;
  final String name;
  final String description;
  final ItemRarity rarity;
  final int baseValue;
  final String iconPath;
  final int maxStackSize;
  final int healthRestore;
  final int staminaRestore;
  final int duration;
  final List<String> buffs;

  const ConsumableData({
    required this.id,
    required this.name,
    required this.description,
    required this.rarity,
    required this.baseValue,
    required this.iconPath,
    required this.maxStackSize,
    required this.healthRestore,
    required this.staminaRestore,
    required this.duration,
    required this.buffs,
  });
}

final class ConsumableDatabaseDef {
  ConsumableDatabaseDef._();
  static const Map<String, ConsumableData> consumables = {
    'health_potion': ConsumableData(
      id: 'health_potion',
      name: 'Health Potion',
      description: 'Restores 50 HP instantly',
      rarity: ItemRarity.common,
      baseValue: 25,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 20,
      staminaRestore: 10,
      duration: 0,
      buffs: const [],
    ),
    'stamina_potion': ConsumableData(
      id: 'stamina_potion',
      name: 'Stamina Potion',
      description: 'Restores 30 stamina instantly',
      rarity: ItemRarity.common,
      baseValue: 20,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 20,
      staminaRestore: 30,
      duration: 0,
      buffs: const [],
    ),
    'super_health_potion': ConsumableData(
      id: 'super_health_potion',
      name: 'Super Health Potion',
      description: 'Restores 150 HP instantly',
      rarity: ItemRarity.rare,
      baseValue: 100,
      iconPath: '',
      maxStackSize: 50,
      healthRestore: 150,
      staminaRestore: 10,
      duration: 0,
      buffs: const [],
    ),
    'cooked_meat': ConsumableData(
      id: 'cooked_meat',
      name: 'Cooked Meat',
      description: 'Delicious cooked meat that restores health',
      rarity: ItemRarity.common,
      baseValue: 15,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 30,
      staminaRestore: 10,
      duration: 0,
      buffs: const [],
    ),
    'strength_elixir': ConsumableData(
      id: 'strength_elixir',
      name: 'Strength Elixir',
      description: 'Increases damage for 60 seconds',
      rarity: ItemRarity.uncommon,
      baseValue: 75,
      iconPath: '',
      maxStackSize: 20,
      healthRestore: 20,
      staminaRestore: 10,
      duration: 60,
      buffs: const ['strength_buff'],
    ),
    'carrot_item': ConsumableData(
      id: 'carrot_item',
      name: 'Carrot',
      description: 'A fresh orange carrot. Can be eaten or sold.',
      rarity: ItemRarity.common,
      baseValue: 15,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 10,
      staminaRestore: 10,
      duration: 0,
      buffs: const [],
    ),
    'strawberry_item': ConsumableData(
      id: 'strawberry_item',
      name: 'Strawberry',
      description: 'A fresh red strawberry. Can be eaten or sold.',
      rarity: ItemRarity.common,
      baseValue: 15,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 10,
      staminaRestore: 10,
      duration: 0,
      buffs: const [],
    ),
    'potato_item': ConsumableData(
      id: 'potato_item',
      name: 'Potato',
      description: 'A starchy potato. Can be cooked or sold.',
      rarity: ItemRarity.common,
      baseValue: 12,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 15,
      staminaRestore: 15,
      duration: 0,
      buffs: const [],
    ),
    'pumpkin_item': ConsumableData(
      id: 'pumpkin_item',
      name: 'Pumpkin',
      description: 'A large orange pumpkin. Great for cooking.',
      rarity: ItemRarity.uncommon,
      baseValue: 35,
      iconPath: '',
      maxStackSize: 50,
      healthRestore: 30,
      staminaRestore: 30,
      duration: 0,
      buffs: const [],
    ),
    'turnip_item': ConsumableData(
      id: 'turnip_item',
      name: 'Turnip',
      description: 'A purple and white turnip. Nutritious vegetable.',
      rarity: ItemRarity.common,
      baseValue: 10,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 8,
      staminaRestore: 8,
      duration: 0,
      buffs: const [],
    ),
    'radish_item': ConsumableData(
      id: 'radish_item',
      name: 'Radish',
      description: 'A crisp radish. Can be eaten or sold.',
      rarity: ItemRarity.common,
      baseValue: 12,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 8,
      staminaRestore: 8,
      duration: 0,
      buffs: const [],
    ),
    'tomato_item': ConsumableData(
      id: 'tomato_item',
      name: 'Tomato',
      description: 'A juicy red tomato. Perfect for salads.',
      rarity: ItemRarity.uncommon,
      baseValue: 20,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 12,
      staminaRestore: 12,
      duration: 0,
      buffs: const [],
    ),
    'corn_item': ConsumableData(
      id: 'corn_item',
      name: 'Corn',
      description: 'Sweet corn on the cob. Can be roasted.',
      rarity: ItemRarity.uncommon,
      baseValue: 18,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 14,
      staminaRestore: 14,
      duration: 0,
      buffs: const [],
    ),
    'apple_item': ConsumableData(
      id: 'apple_item',
      name: 'Apple',
      description: 'A crisp apple. Can be eaten or sold.',
      rarity: ItemRarity.common,
      baseValue: 12,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 8,
      staminaRestore: 8,
      duration: 0,
      buffs: const [],
    ),
  };
}
