import 'package:darkness_dungeon/gameplay/inventory/items/consumable_item.dart';
import 'package:darkness_dungeon/gameplay/inventory/entities/hand/hand_item_id.dart';
import 'package:darkness_dungeon/gameplay/inventory/entities/hand/hand_item_rarity.dart';

final class ConsumableDatabaseDef {
  ConsumableDatabaseDef._();
  static const Map<HandItemId, ConsumableItem> consumables = {
    // HandItemId.health_potion: ConsumableItem(
    //   id: HandItemId.health_potion,
    //   name: 'Health Potion',
    //   description: 'Restores 50 HP instantly',
    //   rarity: HandItemRarity.common,
    //   baseValue: 25,
    //   iconPath: '',
    //   maxStackSize: 99,
    //   healthRestore: 20,
    //   staminaRestore: 10,
    // ),
    // HandItemId.stamina_potion: ConsumableItem(
    //   id: HandItemId.stamina_potion,
    //   name: 'Stamina Potion',
    //   description: 'Restores 30 stamina instantly',
    //   rarity: HandItemRarity.common,
    //   baseValue: 20,
    //   iconPath: '',
    //   maxStackSize: 99,
    //   healthRestore: 20,
    //   staminaRestore: 30,
    // ),
    // HandItemId.super_health_potion: ConsumableItem(
    //   id: HandItemId.super_health_potion,
    //   name: 'Super Health Potion',
    //   description: 'Restores 150 HP instantly',
    //   rarity: HandItemRarity.rare,
    //   baseValue: 100,
    //   iconPath: '',
    //   maxStackSize: 50,
    //   healthRestore: 150,
    //   staminaRestore: 10,
    // ),
    // HandItemId.cooked_meat: ConsumableItem(
    //   id: HandItemId.cooked_meat,
    //   name: 'Cooked Meat',
    //   description: 'Delicious cooked meat that restores health',
    //   rarity: HandItemRarity.common,
    //   baseValue: 15,
    //   iconPath: '',
    //   maxStackSize: 99,
    //   healthRestore: 30,
    //   staminaRestore: 10,
    // ),
    // HandItemId.strength_elixir: ConsumableItem(
    //   id: HandItemId.strength_elixir,
    //   name: 'Strength Elixir',
    //   description: 'Increases damage for 60 seconds',
    //   rarity: HandItemRarity.uncommon,
    //   baseValue: 75,
    //   iconPath: '',
    //   maxStackSize: 20,
    //   healthRestore: 20,
    //   staminaRestore: 10,
    // ),
    HandItemId.carrot_loot_item: ConsumableItem(
      id: HandItemId.carrot_loot_item,
      name: 'Carrot',
      description: 'A fresh orange carrot. Can be eaten or sold.',
      rarity: HandItemRarity.common,
      baseValue: 15,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 10,
      staminaRestore: 10,
    ),
    HandItemId.strawberry_loot_item: ConsumableItem(
      id: HandItemId.strawberry_loot_item,
      name: 'Strawberry',
      description: 'A fresh red strawberry. Can be eaten or sold.',
      rarity: HandItemRarity.common,
      baseValue: 15,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 10,
      staminaRestore: 10,
    ),
    HandItemId.potato_loot_item: ConsumableItem(
      id: HandItemId.potato_loot_item,
      name: 'Potato',
      description: 'A starchy potato. Can be cooked or sold.',
      rarity: HandItemRarity.common,
      baseValue: 12,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 15,
      staminaRestore: 15,
    ),
    HandItemId.pumpkin_loot_item: ConsumableItem(
      id: HandItemId.pumpkin_loot_item,
      name: 'Pumpkin',
      description: 'A large orange pumpkin. Great for cooking.',
      rarity: HandItemRarity.uncommon,
      baseValue: 35,
      iconPath: '',
      maxStackSize: 50,
      healthRestore: 30,
      staminaRestore: 30,
    ),
    HandItemId.turnip_loot_item: ConsumableItem(
      id: HandItemId.turnip_loot_item,
      name: 'Turnip',
      description: 'A purple and white turnip. Nutritious vegetable.',
      rarity: HandItemRarity.common,
      baseValue: 10,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 8,
      staminaRestore: 8,
    ),
    HandItemId.radish_loot_item: ConsumableItem(
      id: HandItemId.radish_loot_item,
      name: 'Radish',
      description: 'A crisp radish. Can be eaten or sold.',
      rarity: HandItemRarity.common,
      baseValue: 12,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 8,
      staminaRestore: 8,
    ),
    HandItemId.tomato_loot_item: ConsumableItem(
      id: HandItemId.tomato_loot_item,
      name: 'Tomato',
      description: 'A juicy red tomato. Perfect for salads.',
      rarity: HandItemRarity.uncommon,
      baseValue: 20,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 12,
      staminaRestore: 12,
    ),
    HandItemId.corn_loot_item: ConsumableItem(
      id: HandItemId.corn_loot_item,
      name: 'Corn',
      description: 'Sweet corn on the cob. Can be roasted.',
      rarity: HandItemRarity.uncommon,
      baseValue: 18,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 14,
      staminaRestore: 14,
    ),
    HandItemId.apple_loot_item: ConsumableItem(
      id: HandItemId.apple_loot_item,
      name: 'Apple',
      description: 'A crisp apple. Can be eaten or sold.',
      rarity: HandItemRarity.common,
      baseValue: 12,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 8,
      staminaRestore: 8,
    ),
    HandItemId.apple: ConsumableItem(
      id: HandItemId.apple,
      name: 'Apple',
      description: 'Fresh apple you can eat or sell.',
      rarity: HandItemRarity.common,
      baseValue: 12,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 8,
      staminaRestore: 8,
    ),
    HandItemId.strawberry: ConsumableItem(
      id: HandItemId.strawberry,
      name: 'Strawberry',
      description: 'Sweet strawberry ready to eat.',
      rarity: HandItemRarity.common,
      baseValue: 15,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 10,
      staminaRestore: 10,
    ),
    HandItemId.tomato: ConsumableItem(
      id: HandItemId.tomato,
      name: 'Tomato',
      description: 'Juicy tomato perfect for salads.',
      rarity: HandItemRarity.uncommon,
      baseValue: 20,
      iconPath: '',
      maxStackSize: 99,
      healthRestore: 12,
      staminaRestore: 12,
    ),
  };
}
