/// Compile-time crop definitions stored directly as `CropEntity` templates.

import '../world/entities/objects/farm/crop_entity.dart';
import '../world/entities/objects/farm/crop_stage_type.dart';

final class CropDatabaseDef {
  CropDatabaseDef._();

  /// Template crops; create runtime instances by copying these.
  static const Map<String, CropEntity> crops = {
    'cabbage': CropEntity(
      cropId: 'cabbage',
      name: 'Cabbage',
      description: 'A leafy green vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'cabbage_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 0,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'radish': CropEntity(
      cropId: 'radish',
      name: 'Radish',
      description: 'A nutritious root vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 7,
      yieldAmount: 6,
      harvestItemId: 'radish_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 1,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'carrot': CropEntity(
      cropId: 'carrot',
      name: 'Carrot',
      description: 'A crunchy orange root vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 7,
      yieldAmount: 3,
      harvestItemId: 'carrot_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 2,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'strawberry': CropEntity(
      cropId: 'strawberry',
      name: 'Strawberry',
      description: 'A nutritious root vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 4,
      yieldAmount: 3,
      harvestItemId: 'strawberry_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 3,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.budding,
    ),
    'apple': CropEntity(
      cropId: 'apple',
      name: 'Apple',
      description: 'Crisp red apple',
      stage: CropStageType.seedling,
      daysPlanted: 0,
      daysToMature: 7,
      yieldAmount: 3,
      harvestItemId: 'apple_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 18,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.budding,
      isTree: true,
    ),
    'wheat': CropEntity(
      cropId: 'wheat',
      name: 'Wheat',
      description: 'Golden wheat grain',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'wheat_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 4,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'pepper': CropEntity(
      cropId: 'pepper',
      name: 'Pepper',
      description: 'Spicy hot peppers',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'pepper_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 5,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'turnip': CropEntity(
      cropId: 'turnip',
      name: 'Turnip',
      description: 'A purple-white root vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'turnip_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 6,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'cotton': CropEntity(
      cropId: 'cotton',
      name: 'Cotton',
      description: 'Soft white cotton',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'cotton_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 7,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'onion': CropEntity(
      cropId: 'onion',
      name: 'Onion',
      description: 'A pungent bulb vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'onion_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 8,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'cauliflower': CropEntity(
      cropId: 'cauliflower',
      name: 'Cauliflower',
      description: 'A white flowering vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'cauliflower_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 9,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'corn': CropEntity(
      cropId: 'corn',
      name: 'Corn',
      description: 'Sweet golden corn',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'corn_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 10,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'tomato': CropEntity(
      cropId: 'tomato',
      name: 'Tomato',
      description: 'Juicy red fruit, perfect for salads',
      stage: CropStageType.seedling,
      daysPlanted: 0,
      daysToMature: 4,
      yieldAmount: 3,
      harvestItemId: 'tomato_item',
      requiredSeason: 'summer',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 11,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.seedling,
    ),
    'grape': CropEntity(
      cropId: 'grape',
      name: 'Grape',
      description: 'Sweet purple grapes',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'grape_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 12,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'prickly_pear': CropEntity(
      cropId: 'prickly_pear',
      name: 'Prickly Pear',
      description: 'Desert cactus fruit',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'prickly_pear_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 13,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'coffee': CropEntity(
      cropId: 'coffee',
      name: 'Coffee',
      description: 'Aromatic coffee beans',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'coffee_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 14,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'zuchini': CropEntity(
      cropId: 'zuchini',
      name: 'Zuchini',
      description: 'Green summer squash',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'zuchini_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 15,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'pumpkin': CropEntity(
      cropId: 'pumpkin',
      name: 'Pumpkin',
      description: 'Large orange pumpkin',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'pumpkin_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 16,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'pineapple': CropEntity(
      cropId: 'pineapple',
      name: 'Pineapple',
      description: 'Tropical sweet fruit',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'pineapple_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 17,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'watermelon': CropEntity(
      cropId: 'watermelon',
      name: 'Watermelon',
      description: 'Large juicy watermelon',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: 'watermelon_item',
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 18,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
  };
}