/// Compile-time game data constants migrated from JSON assets.
/// All values are fully typed to avoid runtime parsing/Map<String, dynamic> usage.

import '../world/entities/objects/farm/crop_stage_type.dart';
import '../inventory/models/item_rarity.dart';

// ----------------------------
// Data models
// ----------------------------

class CropData {
  final String id;
  final String harvestItemId;
  final String name;
  final String description;
  final int? daysToMature;
  final int yieldAmount;
  final String requiredSeason;
  final String spritesheetPath;
  final int spriteWidth;
  final int spriteHeight;
  final int spriteRowIndex;
  final int framesCount;
  final int skipFirstFrames;
  final CropStageType? ySortingFromStage;
  final bool isTree;

  const CropData({
    required this.id,
    required this.harvestItemId,
    required this.name,
    required this.description,
    required this.daysToMature,
    required this.yieldAmount,
    required this.requiredSeason,
    required this.spritesheetPath,
    required this.spriteWidth,
    required this.spriteHeight,
    required this.spriteRowIndex,
    required this.framesCount,
    required this.skipFirstFrames,
    required this.ySortingFromStage,
    this.isTree = false,
  });
}


final class CropDatabaseDef {
  CropDatabaseDef._();

  static const Map<String, CropData> crops = {
    'cabbage': CropData(
      id: 'cabbage',
      harvestItemId: 'cabbage_item',
      name: 'Cabbage',
      description: 'A leafy green vegetable',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 0,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'radish': CropData(
      id: 'radish',
      harvestItemId: 'radish_item',
      name: 'Radish',
      description: 'A nutritious root vegetable',
      daysToMature: 7,
      yieldAmount: 6,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 1,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'carrot': CropData(
      id: 'carrot',
      harvestItemId: 'carrot_item',
      name: 'Carrot',
      description: 'A crunchy orange root vegetable',
      daysToMature: 7,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 2,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'strawberry': CropData(
      id: 'strawberry',
      harvestItemId: 'strawberry_item',
      name: 'Strawberry',
      description: 'A nutritious root vegetable',
      daysToMature: 4,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 3,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.budding,
    ),
    'apple': CropData(
      id: 'apple',
      harvestItemId: 'apple_item',
      name: 'Apple',
      description: 'Crisp red apple',
      daysToMature: 7,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 18,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.budding,
      isTree: true,
    ),
    'wheat': CropData(
      id: 'wheat',
      harvestItemId: 'wheat_item',
      name: 'Wheat',
      description: 'Golden wheat grain',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 4,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'pepper': CropData(
      id: 'pepper',
      harvestItemId: 'pepper_item',
      name: 'Pepper',
      description: 'Spicy hot peppers',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 5,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'turnip': CropData(
      id: 'turnip',
      harvestItemId: 'turnip_item',
      name: 'Turnip',
      description: 'A purple-white root vegetable',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 6,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'cotton': CropData(
      id: 'cotton',
      harvestItemId: 'cotton_item',
      name: 'Cotton',
      description: 'Soft white cotton',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 7,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'onion': CropData(
      id: 'onion',
      harvestItemId: 'onion_item',
      name: 'Onion',
      description: 'A pungent bulb vegetable',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 8,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'cauliflower': CropData(
      id: 'cauliflower',
      harvestItemId: 'cauliflower_item',
      name: 'Cauliflower',
      description: 'A white flowering vegetable',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 9,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'corn': CropData(
      id: 'corn',
      harvestItemId: 'corn_item',
      name: 'Corn',
      description: 'Sweet golden corn',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 10,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'tomato': CropData(
      id: 'tomato',
      harvestItemId: 'tomato_item',
      name: 'Tomato',
      description: 'Juicy red fruit, perfect for salads',
      daysToMature: 4,
      yieldAmount: 3,
      requiredSeason: 'summer',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 11,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.seedling,
    ),
    'grape': CropData(
      id: 'grape',
      harvestItemId: 'grape_item',
      name: 'Grape',
      description: 'Sweet purple grapes',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 12,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'prickly_pear': CropData(
      id: 'prickly_pear',
      harvestItemId: 'prickly_pear_item',
      name: 'Prickly Pear',
      description: 'Desert cactus fruit',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 13,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'coffee': CropData(
      id: 'coffee',
      harvestItemId: 'coffee_item',
      name: 'Coffee',
      description: 'Aromatic coffee beans',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 14,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'zuchini': CropData(
      id: 'zuchini',
      harvestItemId: 'zuchini_item',
      name: 'Zuchini',
      description: 'Green summer squash',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 15,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'pumpkin': CropData(
      id: 'pumpkin',
      harvestItemId: 'pumpkin_item',
      name: 'Pumpkin',
      description: 'Large orange pumpkin',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 16,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'pineapple': CropData(
      id: 'pineapple',
      harvestItemId: 'pineapple_item',
      name: 'Pineapple',
      description: 'Tropical sweet fruit',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 17,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    'watermelon': CropData(
      id: 'watermelon',
      harvestItemId: 'watermelon_item',
      name: 'Watermelon',
      description: 'Large juicy watermelon',
      daysToMature: null,
      yieldAmount: 3,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 18,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
  };
}