import 'package:darkness_dungeon/gameplay/inventory/items/seed_item.dart';
import 'package:darkness_dungeon/gameplay/inventory/entities/hand/hand_item_id.dart';
import 'package:darkness_dungeon/gameplay/inventory/entities/hand/hand_item_rarity.dart';

final class SeedDatabaseDef {
  static const Map<HandItemId, SeedItem> seeds = {
    HandItemId.carrot_seeds: SeedItem(
      id: HandItemId.carrot_seeds,
      name: 'Carrot Seeds',
      description: 'Plant to grow carrots in any season',
      rarity: HandItemRarity.common,
      baseValue: 10,
      iconPath: 'assets/images/items/carrot_seeds.png',
      maxStackSize: 99,
      cropId: 'carrot',
      growthTime: 4,
      yield: 3,
      season: 'any',
    ),
    HandItemId.wheat_seeds: SeedItem(
      id: HandItemId.wheat_seeds,
      name: 'Wheat Seeds',
      description: 'Grow wheat in spring or fall',
      rarity: HandItemRarity.common,
      baseValue: 8,
      iconPath: 'assets/images/items/wheat_seeds.png',
      maxStackSize: 99,
      cropId: 'wheat',
      growthTime: 5,
      yield: 4,
      season: 'spring',
    ),
    HandItemId.tomato_seeds: SeedItem(
      id: HandItemId.tomato_seeds,
      name: 'Tomato Seeds',
      description: 'Summer crop that produces many tomatoes',
      rarity: HandItemRarity.uncommon,
      baseValue: 25,
      iconPath: 'assets/images/items/tomato_seeds.png',
      maxStackSize: 99,
      cropId: 'tomato',
      growthTime: 7,
      yield: 6,
      season: 'summer',
    ),
    HandItemId.pumpkin_seeds: SeedItem(
      id: HandItemId.pumpkin_seeds,
      name: 'Pumpkin Seeds',
      description: 'Fall crop that grows large pumpkins',
      rarity: HandItemRarity.uncommon,
      baseValue: 30,
      iconPath: 'assets/images/items/pumpkin_seeds.png',
      maxStackSize: 99,
      cropId: 'pumpkin',
      growthTime: 10,
      yield: 2,
      season: 'fall',
    ),
    HandItemId.ancient_seeds: SeedItem(
      id: HandItemId.ancient_seeds,
      name: 'Ancient Seeds',
      description: 'Rare ancient seeds that grow valuable crops',
      rarity: HandItemRarity.legendary,
      baseValue: 500,
      iconPath: 'assets/images/items/ancient_seeds.png',
      maxStackSize: 10,
      cropId: 'ancient_fruit',
      growthTime: 28,
      yield: 10,
      season: 'any',
    ),
  };
}
