import 'package:darkness_dungeon/gameplay/inventory/items/seed_item.dart';
import 'package:darkness_dungeon/gameplay/inventory/models/item_rarity.dart';

final class SeedDatabaseDef {
  static const Map<String, SeedItem> seeds = {
    'carrot_seeds': SeedItem(
      id: 'carrot_seeds',
      name: 'Carrot Seeds',
      description: 'Plant to grow carrots in any season',
      rarity: ItemRarity.common,
      baseValue: 10,
      iconPath: 'assets/images/items/carrot_seeds.png',
      maxStackSize: 99,
      cropId: 'carrot',
      growthTime: 4,
      yield: 3,
      season: 'any',
    ),
    'wheat_seeds': SeedItem(
      id: 'wheat_seeds',
      name: 'Wheat Seeds',
      description: 'Grow wheat in spring or fall',
      rarity: ItemRarity.common,
      baseValue: 8,
      iconPath: 'assets/images/items/wheat_seeds.png',
      maxStackSize: 99,
      cropId: 'wheat',
      growthTime: 5,
      yield: 4,
      season: 'spring',
    ),
    'tomato_seeds': SeedItem(
      id: 'tomato_seeds',
      name: 'Tomato Seeds',
      description: 'Summer crop that produces many tomatoes',
      rarity: ItemRarity.uncommon,
      baseValue: 25,
      iconPath: 'assets/images/items/tomato_seeds.png',
      maxStackSize: 99,
      cropId: 'tomato',
      growthTime: 7,
      yield: 6,
      season: 'summer',
    ),
    'pumpkin_seeds': SeedItem(
      id: 'pumpkin_seeds',
      name: 'Pumpkin Seeds',
      description: 'Fall crop that grows large pumpkins',
      rarity: ItemRarity.uncommon,
      baseValue: 30,
      iconPath: 'assets/images/items/pumpkin_seeds.png',
      maxStackSize: 99,
      cropId: 'pumpkin',
      growthTime: 10,
      yield: 2,
      season: 'fall',
    ),
    'ancient_seeds': SeedItem(
      id: 'ancient_seeds',
      name: 'Ancient Seeds',
      description: 'Rare ancient seeds that grow valuable crops',
      rarity: ItemRarity.legendary,
      baseValue: 500,
      iconPath: 'assets/images/items/ancient_seeds.png',
      maxStackSize: 10,
      cropId: 'ancient_fruit',
      growthTime: 28,
      yield: 10,
      season: 'any',
    ),
  };
}
