import 'package:darkness_dungeon/gameplay/inventory/items/main_hand_item.dart';
import 'package:darkness_dungeon/gameplay/inventory/models/equipped_hand_type.dart';
import 'package:darkness_dungeon/gameplay/inventory/models/item_rarity.dart';

final class ItemWeaponDatabaseDef {
  ItemWeaponDatabaseDef._();

  static const Map<String, MainHandItem> weapons = {
    'harvestBasket': MainHandItem(
      id: 'harvestBasket',
      name: 'Harvest Basket',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: EquippedHandType.harvestBasket,
    ),
    'strawberry': MainHandItem(
      id: 'strawberry',
      name: 'Strawberry',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: EquippedHandType.strawberry,
    ),
    'apple': MainHandItem(
      id: 'apple',
      name: 'Apple',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: EquippedHandType.apple,
    ),
    'tomato': MainHandItem(
      id: 'tomato',
      name: 'Tomato',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: EquippedHandType.tomato,
    ),
    'strawberry_seed_bag': MainHandItem(
      id: 'strawberry_seed_bag',
      name: 'Strawberry Seed Bag',
      description: 'Plant these to grow strawberries',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: EquippedHandType.strawberry_seed_bag,
      cropId: 'strawberry',
      isStackable: true,
      maxStackSize: 99,
    ),
    'apple_seed_bag': MainHandItem(
      id: 'apple_seed_bag',
      name: 'Apple Seed Bag',
      description: 'Plant these to grow apples',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: EquippedHandType.apple_seed_bag,
      cropId: 'apple',
      isStackable: true,
      maxStackSize: 99,
    ),
    'radish_seed_bag': MainHandItem(
      id: 'radish_seed_bag',
      name: 'Radish Seed Bag',
      description: 'Plant these to grow radishes',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: EquippedHandType.radish_seed_bag,
      cropId: 'radish',
      isStackable: true,
      maxStackSize: 99,
    ),
    'tomato_seed_bag': MainHandItem(
      id: 'tomato_seed_bag',
      name: 'Tomato Seed Bag',
      description: 'Plant these to grow tomatoes',
      rarity: ItemRarity.common,
      baseValue: 60,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: EquippedHandType.tomato_seed_bag,
      cropId: 'tomato',
      isStackable: true,
      maxStackSize: 99,
    ),
    'shovel': MainHandItem(
      id: 'shovel',
      name: 'Shovel',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: EquippedHandType.shovel,
    ),
    'wateringCan': MainHandItem(
      id: 'wateringCan',
      name: 'Watering Can',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: EquippedHandType.wateringCan,
    ),
    'staff': MainHandItem(
      id: 'staff',
      name: 'Staff',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: EquippedHandType.staff,
    ),
    'ironSword': MainHandItem(
      id: 'ironSword',
      name: 'Iron Sword',
      description: 'A sturdy iron sword for basic combat',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: EquippedHandType.ironSword,
    ),
    'steel_axe': MainHandItem(
      id: 'steel_axe',
      name: 'Steel Axe',
      description: 'A heavy steel axe with high damage',
      rarity: ItemRarity.uncommon,
      baseValue: 180,
      iconPath: 'assets/images/items/steel_axe.png',
      damage: 25,
      attackSpeed: 0.8,
      critChance: 0.08,
      critMultiplier: 1.8,
      equippedHandType: EquippedHandType.axe,
    ),
    'legendary_blade': MainHandItem(
      id: 'legendary_blade',
      name: 'Legendary Blade',
      description: 'A mythical sword forged by ancient smiths',
      rarity: ItemRarity.legendary,
      baseValue: 5000,
      iconPath: 'assets/images/items/legendary_blade.png',
      damage: 80,
      attackSpeed: 1.5,
      critChance: 0.25,
      critMultiplier: 2.5,
      equippedHandType: EquippedHandType.sword,
    ),
    'fire_staff': MainHandItem(
      id: 'fire_staff',
      name: 'Fire Staff',
      description: 'A magical staff that shoots fireballs',
      rarity: ItemRarity.rare,
      baseValue: 350,
      iconPath: 'assets/images/items/fire_staff.png',
      damage: 20,
      attackSpeed: 1.0,
      critChance: 0.1,
      critMultiplier: 2.0,
      equippedHandType: EquippedHandType.staff,
    ),
    'ice_wand': MainHandItem(
      id: 'ice_wand',
      name: 'Ice Wand',
      description: 'A magical wand that shoots ice projectiles',
      rarity: ItemRarity.uncommon,
      baseValue: 200,
      iconPath: 'assets/images/items/ice_wand.png',
      damage: 12,
      attackSpeed: 1.3,
      critChance: 0.07,
      critMultiplier: 1.6,
      equippedHandType: EquippedHandType.wand,
    ),
  };
}
