import 'package:darkness_dungeon/gameplay/inventory/items/main_hand_item.dart';
import 'package:darkness_dungeon/gameplay/inventory/entities/hand_item_id.dart';
import 'package:darkness_dungeon/gameplay/inventory/models/item_rarity.dart';

final class ItemWeaponDatabaseDef {
  ItemWeaponDatabaseDef._();

  /// Authoritative weapon definitions keyed by EquippedHandType to keep
  /// id/equippedHandType/map key aligned.
  static const Map<HandItemId, MainHandItem> weaponsByHandType = {
    HandItemId.harvestBasket: MainHandItem(
      id: HandItemId.harvestBasket,
      name: 'Harvest Basket',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: HandItemId.harvestBasket,
    ),
    HandItemId.strawberry: MainHandItem(
      id: HandItemId.strawberry,
      name: 'Strawberry',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: HandItemId.strawberry,
    ),
    HandItemId.apple: MainHandItem(
      id: HandItemId.apple,
      name: 'Apple',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: HandItemId.apple,
    ),
    HandItemId.tomato: MainHandItem(
      id: HandItemId.tomato,
      name: 'Tomato',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: HandItemId.tomato,
    ),
    HandItemId.strawberry_seed_bag: MainHandItem(
      id: HandItemId.strawberry_seed_bag,
      name: 'Strawberry Seed Bag',
      description: 'Plant these to grow strawberries',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: HandItemId.strawberry_seed_bag,
      cropId: 'strawberry',
      isStackable: true,
      maxStackSize: 99,
    ),
    HandItemId.apple_seed_bag: MainHandItem(
      id: HandItemId.apple_seed_bag,
      name: 'Apple Seed Bag',
      description: 'Plant these to grow apples',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: HandItemId.apple_seed_bag,
      cropId: 'apple',
      isStackable: true,
      maxStackSize: 99,
    ),
    HandItemId.radish_seed_bag: MainHandItem(
      id: HandItemId.radish_seed_bag,
      name: 'Radish Seed Bag',
      description: 'Plant these to grow radishes',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: HandItemId.radish_seed_bag,
      cropId: 'radish',
      isStackable: true,
      maxStackSize: 99,
    ),
    HandItemId.tomato_seed_bag: MainHandItem(
      id: HandItemId.tomato_seed_bag,
      name: 'Tomato Seed Bag',
      description: 'Plant these to grow tomatoes',
      rarity: ItemRarity.common,
      baseValue: 60,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: HandItemId.tomato_seed_bag,
      cropId: 'tomato',
      isStackable: true,
      maxStackSize: 99,
    ),
    HandItemId.shovel: MainHandItem(
      id: HandItemId.shovel,
      name: 'Shovel',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: HandItemId.shovel,
    ),
    HandItemId.wateringCan: MainHandItem(
      id: HandItemId.wateringCan,
      name: 'Watering Can',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: HandItemId.wateringCan,
    ),
    HandItemId.staff: MainHandItem(
      id: HandItemId.staff,
      name: 'Staff',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: HandItemId.staff,
    ),
    HandItemId.ironSword: MainHandItem(
      id: HandItemId.ironSword,
      name: 'Iron Sword',
      description: 'A sturdy iron sword for basic combat',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: HandItemId.ironSword,
    ),
    HandItemId.axe: MainHandItem(
      id: HandItemId.axe,
      name: 'Steel Axe',
      description: 'A heavy steel axe with high damage',
      rarity: ItemRarity.uncommon,
      baseValue: 180,
      iconPath: 'assets/images/items/steel_axe.png',
      damage: 25,
      attackSpeed: 0.8,
      critChance: 0.08,
      critMultiplier: 1.8,
      equippedHandType: HandItemId.axe,
    ),
    HandItemId.sword: MainHandItem(
      id: HandItemId.sword,
      name: 'Legendary Blade',
      description: 'A mythical sword forged by ancient smiths',
      rarity: ItemRarity.legendary,
      baseValue: 5000,
      iconPath: 'assets/images/items/legendary_blade.png',
      damage: 80,
      attackSpeed: 1.5,
      critChance: 0.25,
      critMultiplier: 2.5,
      equippedHandType: HandItemId.sword,
    ),
    HandItemId.staff_fire: MainHandItem(
      id: HandItemId.staff_fire,
      name: 'Fire Staff',
      description: 'A magical staff that shoots fireballs',
      rarity: ItemRarity.rare,
      baseValue: 350,
      iconPath: 'assets/images/items/fire_staff.png',
      damage: 20,
      attackSpeed: 1.0,
      critChance: 0.1,
      critMultiplier: 2.0,
      equippedHandType: HandItemId.staff_fire,
    ),
    HandItemId.wand: MainHandItem(
      id: HandItemId.wand,
      name: 'Ice Wand',
      description: 'A magical wand that shoots ice projectiles',
      rarity: ItemRarity.uncommon,
      baseValue: 200,
      iconPath: 'assets/images/items/ice_wand.png',
      damage: 12,
      attackSpeed: 1.3,
      critChance: 0.07,
      critMultiplier: 1.6,
      equippedHandType: HandItemId.wand,
    ),
  };

  /// Enum-keyed view mirroring weaponsByHandType for consumers expecting a mutable map.
  static final Map<HandItemId, MainHandItem> weapons = {
    for (final entry in weaponsByHandType.entries) entry.key: entry.value,
  };
}
