import 'package:darkness_dungeon/gameplay/inventory/models/item_rarity.dart';

class WeaponData {
  final String id;
  final String name;
  final String description;
  final ItemRarity rarity;
  final int baseValue;
  final String iconPath;
  final int damage;
  final double attackSpeed;
  final double critChance;
  final double critMultiplier;
  final String equippedHandType;
  final String? cropId;
  final bool isStackable;
  final int maxStackSize;

  const WeaponData({
    required this.id,
    required this.name,
    required this.description,
    required this.rarity,
    required this.baseValue,
    required this.iconPath,
    required this.damage,
    required this.attackSpeed,
    required this.critChance,
    required this.critMultiplier,
    required this.equippedHandType,
    this.cropId,
    this.isStackable = false,
    this.maxStackSize = 1,
  });
}

final class ItemWeaponDatabaseDef {
  ItemWeaponDatabaseDef._();

  static const Map<String, WeaponData> weapons = {
    'harvestBasket': WeaponData(
      id: 'harvestBasket',
      name: 'Harvest Basket',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: 'harvestBasket',
    ),
    'strawberry': WeaponData(
      id: 'strawberry',
      name: 'Strawberry',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: 'strawberry',
    ),
    'apple': WeaponData(
      id: 'apple',
      name: 'Apple',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: 'apple',
    ),
    'tomato': WeaponData(
      id: 'tomato',
      name: 'Tomato',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: 'tomato',
    ),
    'strawberry_seed_bag': WeaponData(
      id: 'strawberry_seed_bag',
      name: 'Strawberry Seed Bag',
      description: 'Plant these to grow strawberries',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: 'strawberry_seed_bag',
      cropId: 'strawberry',
      isStackable: true,
      maxStackSize: 99,
    ),
    'apple_seed_bag': WeaponData(
      id: 'apple_seed_bag',
      name: 'Apple Seed Bag',
      description: 'Plant these to grow apples',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: 'apple_seed_bag',
      cropId: 'apple',
      isStackable: true,
      maxStackSize: 99,
    ),
    'radish_seed_bag': WeaponData(
      id: 'radish_seed_bag',
      name: 'Radish Seed Bag',
      description: 'Plant these to grow radishes',
      rarity: ItemRarity.common,
      baseValue: 50,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: 'radish_seed_bag',
      cropId: 'radish',
      isStackable: true,
      maxStackSize: 99,
    ),
    'tomato_seed_bag': WeaponData(
      id: 'tomato_seed_bag',
      name: 'Tomato Seed Bag',
      description: 'Plant these to grow tomatoes',
      rarity: ItemRarity.common,
      baseValue: 60,
      iconPath: '',
      damage: 0,
      attackSpeed: 1.0,
      critChance: 0.0,
      critMultiplier: 1.0,
      equippedHandType: 'tomato_seed_bag',
      cropId: 'tomato',
      isStackable: true,
      maxStackSize: 99,
    ),
    'shovel': WeaponData(
      id: 'shovel',
      name: 'Shovel',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: 'shovel',
    ),
    'wateringCan': WeaponData(
      id: 'wateringCan',
      name: 'Watering Can',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: 'wateringCan',
    ),
    'staff': WeaponData(
      id: 'staff',
      name: 'Staff',
      description: 'TODO',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: 'staff',
    ),
    'ironSword': WeaponData(
      id: 'ironSword',
      name: 'Iron Sword',
      description: 'A sturdy iron sword for basic combat',
      rarity: ItemRarity.common,
      baseValue: 100,
      iconPath: '',
      damage: 15,
      attackSpeed: 1.2,
      critChance: 0.05,
      critMultiplier: 1.5,
      equippedHandType: 'ironSword',
    ),
    'steel_axe': WeaponData(
      id: 'steel_axe',
      name: 'Steel Axe',
      description: 'A heavy steel axe with high damage',
      rarity: ItemRarity.uncommon,
      baseValue: 180,
      iconPath: 'assets/images/items/steel_axe.png',
      damage: 25,
      attackSpeed: 0.8,
      critChance: 0.08,
      critMultiplier: 1.8,
      equippedHandType: 'axe',
    ),
    'legendary_blade': WeaponData(
      id: 'legendary_blade',
      name: 'Legendary Blade',
      description: 'A mythical sword forged by ancient smiths',
      rarity: ItemRarity.legendary,
      baseValue: 5000,
      iconPath: 'assets/images/items/legendary_blade.png',
      damage: 80,
      attackSpeed: 1.5,
      critChance: 0.25,
      critMultiplier: 2.5,
      equippedHandType: 'sword',
    ),
    'fire_staff': WeaponData(
      id: 'fire_staff',
      name: 'Fire Staff',
      description: 'A magical staff that shoots fireballs',
      rarity: ItemRarity.rare,
      baseValue: 350,
      iconPath: 'assets/images/items/fire_staff.png',
      damage: 20,
      attackSpeed: 1.0,
      critChance: 0.1,
      critMultiplier: 2.0,
      equippedHandType: 'staff',
    ),
    'ice_wand': WeaponData(
      id: 'ice_wand',
      name: 'Ice Wand',
      description: 'A magical wand that shoots ice projectiles',
      rarity: ItemRarity.uncommon,
      baseValue: 200,
      iconPath: 'assets/images/items/ice_wand.png',
      damage: 12,
      attackSpeed: 1.3,
      critChance: 0.07,
      critMultiplier: 1.6,
      equippedHandType: 'wand',
    ),
  };
}
