import 'dart:typed_data';

import 'package:flutter_scene/scene.dart' show Node;
import 'package:vector_math/vector_math.dart';
import 'package:voxel_engine/content.dart';
import 'package:voxel_engine/core.dart';
import 'package:voxel_scene/voxel_scene.dart';
import 'package:voxel_engine/worldgen.dart';

/// Called after a block changes: the cell, what was there, what is there now.
typedef BlockChangedListener = void Function(IVec3 cell, int oldId, int newId);

/// How one liquid kind flows in a [GameWorld].
class LiquidSpec {
  /// A liquid stepping every [period] seconds, spreading [reach] cells from a
  /// source.
  const LiquidSpec({this.period = 0.25, this.reach = 4});

  /// Seconds between steps.
  final double period;

  /// Cells a source feeds sideways.
  final int reach;
}

/// The world of a game: blocks streamed around a focus point, generated from
/// a [WorldGenSpec], meshed on worker isolates (or on this one, headless),
/// drawn by a [VoxelChunkView], with liquids that flow. What bodies, rays and
/// paths read ([VoxelQuery]) and what tools write ([VoxelEditor]).
class GameWorld implements VoxelEditor {
  GameWorld._(this.blocks, this.generator, this._jobs, {required int loadRadius, required this.headless, Map<String, LiquidSpec> liquids = const {}}) {
    _view = headless ? null : VoxelChunkView();
    _streamer = ChunkStreamer(table: blocks.table, sink: _view ?? _NoSink(), loadRadius: loadRadius);
    flow = LiquidFlow(
      table: blocks.table,
      rules: [
        for (final kind in blocks.liquidKinds)
          _hasFlowingForm(kind)
              ? LiquidRule(
                  flowingId: blocks.flowingOf(kind),
                  period: (liquids[kind] ?? _defaultLiquid(kind)).period,
                  reach: (liquids[kind] ?? _defaultLiquid(kind)).reach,
                )
              // A liquid without a flowing form stays where it is put.
              : LiquidRule(flowingId: blocks.indexOf(kind), period: double.infinity, reach: 0),
      ],
      canEnter: blocks.isReplaceable,
    );
  }

  /// A world of [blocks] generated by [spec] under [seed], meshed on a pool of
  /// worker isolates; call [start] before the first [update].
  factory GameWorld(BlockRegistry<BlockType> blocks, WorldGenSpec spec, int seed,
      {int loadRadius = 6, Map<String, LiquidSpec> liquids = const {}}) {
    final generator = spec.compile(blocks.ids, seed);
    return GameWorld._(blocks, generator, null, loadRadius: loadRadius, headless: false, liquids: liquids);
  }

  /// The same world with no renderer and no isolates: chunks are generated and
  /// meshed on this isolate as they are asked for. For tests and servers.
  factory GameWorld.headless(BlockRegistry<BlockType> blocks, WorldGenSpec spec, int seed,
      {int loadRadius = 2, Map<String, LiquidSpec> liquids = const {}}) {
    final generator = spec.compile(blocks.ids, seed);
    return GameWorld._(blocks, generator, _LocalJobs(generator, blocks.table),
        loadRadius: loadRadius, headless: true, liquids: liquids);
  }

  static LiquidSpec _defaultLiquid(String kind) => kind == 'lava' ? const LiquidSpec(period: 0.6, reach: 2) : const LiquidSpec();

  bool _hasFlowingForm(String kind) => blocks.types.any((t) => t.liquid == kind && !t.liquidSource);

  /// The game's blocks.
  final BlockRegistry<BlockType> blocks;

  /// The world's generator, for terrain questions (height, biome, structures).
  final SpecGenerator generator;

  /// Whether there is no renderer and no worker pool.
  final bool headless;

  final ChunkJobs? _jobs;
  VoxelChunkView? _view;
  late final ChunkStreamer _streamer;
  ChunkWorkerPool? _pool;

  /// The liquids' flow; host-only in a networked game ([LiquidFlow.enabled]).
  late final LiquidFlow flow;

  final List<BlockChangedListener> _listeners = [];

  /// The chunk nodes to add to the scene; null headless.
  Node? get root => _view?.root;

  /// Starts the worker isolates (none headless). The factory is built in a
  /// static so the closure sent to them captures only sendable values.
  Future<void> start() async {
    final local = _jobs;
    if (local != null) {
      _streamer.jobs = local;
      return;
    }
    _pool?.dispose();
    final pool = ChunkWorkerPool(ChunkWorkerConfig(
      generator: _factory(generator.spec, blocks.ids, generator.seed),
      table: blocks.table,
    ));
    await pool.start();
    _pool = pool;
    _streamer.jobs = pool;
  }

  static ChunkGeneratorFactory _factory(WorldGenSpec spec, Map<String, int> ids, int seed) => () => spec.compile(ids, seed);

  /// Stops the worker isolates.
  void dispose() {
    _pool?.dispose();
    _pool = null;
    _streamer.jobs = null;
  }

  /// How far chunks are kept around the focus, in chunks.
  int get loadRadius => _streamer.loadRadius;

  set loadRadius(int value) {
    _streamer
      ..loadRadius = value
      ..unloadRadius = value + 2;
  }

  /// Streams the window around [focus] and lands the jobs that finished; once
  /// a frame.
  void update(Vector3 focus) {
    _streamer.updateAround(ChunkStreamer.chunkOfXZ(focus.x.floor(), focus.z.floor()));
    _streamer.update();
  }

  /// Advances the liquids by [dt]; once a simulation step.
  void tickFlow(double dt) => flow.tick(this, dt);

  /// Whether nothing is waiting to be generated or meshed.
  bool get isIdle => _streamer.isIdle;

  /// How many chunks have a mesh.
  int get meshCount => _streamer.meshCount;

  /// How many chunks are loaded.
  int get loadedChunkCount => _streamer.loadedChunkCount;

  /// How bright the sky's baked light shows (1 noon, ~0.35 night).
  void setSkyIntensity(double value) => _view?.setSkyIntensity(value);

  @override
  VoxelBlockTable get table => blocks.table;

  @override
  int getBlockXYZ(int x, int y, int z) => _streamer.getBlockXYZ(x, y, z);

  /// The block at [cell].
  int getBlock(IVec3 cell) => _streamer.getBlockXYZ(cell.x, cell.y, cell.z);

  /// The id (name) of the block at [cell].
  String blockNameAt(IVec3 cell) => blocks.idOf(getBlock(cell));

  /// Whether [cell]'s chunk is loaded.
  bool isLoaded(IVec3 cell) => _streamer.chunks.containsKey(ChunkStreamer.chunkOf(cell));

  /// Whether the block at [cell] stops a body; below the world counts.
  bool isSolid(IVec3 cell) => cell.y < 0 || blocks.table.isSolid(getBlock(cell));

  /// (sky, block) light of [cell], 0..15 each.
  CellLight lightAt(IVec3 cell) => _streamer.lightAt(cell);

  @override
  bool setBlock(IVec3 cell, int id) {
    final old = getBlock(cell);
    if (!_streamer.setBlock(cell, id)) return false;
    flow.touch(this, cell, old, id);
    for (final l in List.of(_listeners)) {
      l(cell, old, id);
    }
    return true;
  }

  /// Writes [id] at [cell] now, or when its chunk generates if it is not
  /// loaded: an edit that must not be lost (another player's).
  void storeEdit(IVec3 cell, int id) {
    if (isLoaded(cell)) {
      setBlock(cell, id);
    } else {
      _streamer.storeEdit(cell, id);
    }
  }

  /// Writes block [name] at [cell]; false when its chunk is not loaded.
  bool setBlockNamed(IVec3 cell, String name) => setBlock(cell, blocks.indexOf(name));

  /// Every edit made to the generated world, by dimension and chunk: what a
  /// save keeps. Live maps; copy before changing.
  EditsByDimension get edits => _streamer.editsByDimension;

  /// Replaces the edits (a save read back); call before the first [update].
  void replaceEdits(EditsByDimension all) => _streamer.replaceEdits(all);

  /// Cells edited so far.
  int get editCount => _streamer.editCount;

  /// Calls [listener] after every block change.
  void addListener(BlockChangedListener listener) => _listeners.add(listener);

  /// Stops calling [listener].
  void removeListener(BlockChangedListener listener) => _listeners.remove(listener);

  /// The first air cell above the highest solid block of column ([x], [z])
  /// among loaded chunks, or the generator's surface where the chunk is not
  /// loaded yet.
  int groundHeight(int x, int z) {
    final chunk = _streamer.chunks[ChunkStreamer.chunkOfXZ(x, z)];
    if (chunk == null) return generator.surfaceHeight(x, z);
    final lx = x - (x / ChunkSize.sizeX).floor() * ChunkSize.sizeX;
    final lz = z - (z / ChunkSize.sizeZ).floor() * ChunkSize.sizeZ;
    for (var y = ChunkSize.sizeY - 1; y >= 0; y--) {
      if (blocks.table.isSolid(chunk[ChunkSize.index(lx, y, lz)])) return y + 1;
    }
    return 0;
  }
}

class _NoSink implements ChunkMeshSink {
  @override
  void apply(ChunkPos pos, ChunkMeshResult result) {}

  @override
  void remove(ChunkPos pos) {}
}

class _LocalJobs implements ChunkJobs {
  _LocalJobs(this.generator, VoxelBlockTable table) : _mesher = table.mesher();

  final SpecGenerator generator;
  final ChunkMesher _mesher;

  @override
  Future<Uint8List> generate(int cx, int cz, [int dimension = 0]) => Future.value(generator.generateIn(cx, cz, dimension));

  @override
  Future<ChunkMeshResult> mesh(int cx, int cz, List<Uint8List?> ring) => Future.value(_mesher.build(cx, cz, ring));
}
