import 'package:darkness_dungeon/gameplay/inventory/entities/hand/hand_item_id.dart';

import '../../world/entities/objects/farm/crop_entity.dart';
import '../../world/entities/objects/farm/crop_stage_type.dart';

final class ModernFarmCropEntityDatabaseDef {
  ModernFarmCropEntityDatabaseDef._();

  static const Map<HandItemId, CropEntity> cropEntityList = {
    HandItemId.cabbage: CropEntity(
      cropId: HandItemId.cabbage,
      name: 'Cabbage',
      description: 'A leafy green vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.cabbage_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 0,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.radish: CropEntity(
      cropId: HandItemId.radish,
      name: 'Radish',
      description: 'A nutritious root vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 7,
      yieldAmount: 6,
      harvestItemId: HandItemId.radish_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 1,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.carrot: CropEntity(
      cropId: HandItemId.carrot,
      name: 'Carrot',
      description: 'A crunchy orange root vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 7,
      yieldAmount: 3,
      harvestItemId: HandItemId.carrot_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 2,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.strawberry: CropEntity(
      cropId: HandItemId.strawberry,
      name: 'Strawberry',
      description: 'A nutritious root vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 4,
      yieldAmount: 3,
      harvestItemId: HandItemId.strawberry_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 3,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.budding,
    ),
    HandItemId.apple: CropEntity(
      cropId: HandItemId.apple,
      name: 'Apple',
      description: 'Crisp red apple',
      stage: CropStageType.seedling,
      daysPlanted: 0,
      daysToMature: 7,
      yieldAmount: 3,
      harvestItemId: HandItemId.apple_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 18,
      framesCount: 7,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.budding,
      isTree: true,
    ),
    HandItemId.wheat: CropEntity(
      cropId: HandItemId.wheat,
      name: 'Wheat',
      description: 'Golden wheat grain',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.wheat_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 4,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.pepper: CropEntity(
      cropId: HandItemId.pepper,
      name: 'Pepper',
      description: 'Spicy hot peppers',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.pepper_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 5,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.turnip: CropEntity(
      cropId: HandItemId.turnip,
      name: 'Turnip',
      description: 'A purple-white root vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.turnip_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 6,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.cotton: CropEntity(
      cropId: HandItemId.cotton,
      name: 'Cotton',
      description: 'Soft white cotton',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.cotton_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 7,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.onion: CropEntity(
      cropId: HandItemId.onion,
      name: 'Onion',
      description: 'A pungent bulb vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.onion_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 8,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.cauliflower: CropEntity(
      cropId: HandItemId.cauliflower,
      name: 'Cauliflower',
      description: 'A white flowering vegetable',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.cauliflower_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 9,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.corn: CropEntity(
      cropId: HandItemId.corn,
      name: 'Corn',
      description: 'Sweet golden corn',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.corn_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 10,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.tomato: CropEntity(
      cropId: HandItemId.tomato,
      name: 'Tomato',
      description: 'Juicy red fruit, perfect for salads',
      stage: CropStageType.seedling,
      daysPlanted: 0,
      daysToMature: 4,
      yieldAmount: 3,
      harvestItemId: HandItemId.tomato_loot_item,
      requiredSeason: 'summer',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 11,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: CropStageType.seedling,
    ),
    HandItemId.grape: CropEntity(
      cropId: HandItemId.grape,
      name: 'Grape',
      description: 'Sweet purple grapes',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.grape_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 12,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.prickly_pear: CropEntity(
      cropId: HandItemId.prickly_pear,
      name: 'Prickly Pear',
      description: 'Desert cactus fruit',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.prickly_pear_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 13,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.coffee: CropEntity(
      cropId: HandItemId.coffee,
      name: 'Coffee',
      description: 'Aromatic coffee beans',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.coffee_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 14,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.zuchini: CropEntity(
      cropId: HandItemId.zuchini,
      name: 'Zuchini',
      description: 'Green summer squash',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.zuchini_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 15,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.pumpkin: CropEntity(
      cropId: HandItemId.pumpkin,
      name: 'Pumpkin',
      description: 'Large orange pumpkin',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.pumpkin_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 16,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.pineapple: CropEntity(
      cropId: HandItemId.pineapple,
      name: 'Pineapple',
      description: 'Tropical sweet fruit',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.pineapple_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 17,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
    HandItemId.watermelon: CropEntity(
      cropId: HandItemId.watermelon,
      name: 'Watermelon',
      description: 'Large juicy watermelon',
      stage: CropStageType.planted,
      daysPlanted: 0,
      daysToMature: 0,
      yieldAmount: 3,
      harvestItemId: HandItemId.watermelon_loot_item,
      requiredSeason: 'any',
      spritesheetPath: 'tiled/Modern_Farm_v1.2/tilesets/4_Crops_16x16.png',
      spriteWidth: 16,
      spriteHeight: 32,
      spriteRowIndex: 18,
      framesCount: 4,
      skipFirstFrames: 1,
      ySortingFromStage: null,
    ),
  };
}
