#!/usr/bin/env python3
"""Pipeline step 10 — generate `component_keys.dart` from the component classes (SSOT).

The Dart twin of the Godot repo's `10_generate_component_keys.py`. A component's
container key is its concrete class name — `IComponent.componentKey` resolves
`runtimeType.toString()` at registration — so the source of this generator is the
`class` declaration itself, never a hand-kept constant that could drift (rule 16).

Only classes under `lib/src/core/components/` whose `extends` chain reaches
`IComponent` get a key: they are exactly the ones a container can register.
The chain is resolved (not tested one level deep) because a component may
inherit through an intermediate base (`HealthComponent` → `IComponentVital` →
`IComponent`). `abstract` classes are contracts, never registered instances —
no key.

`HealthComponent` → `health`, `IComponentSquad` → `squad`: both affixes say
"component" and neither carries information once the constant lives on a class
called `ComponentKeys`.

    .venv/bin/python dawnforge.py component-keys [--dry-run|--check]
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(next(
    p / "lib" for p in Path(__file__).resolve().parents
    if (p / "lib" / "project_paths.py").is_file())))
from project_paths import COMPONENTS_ROOT, GENERATED_DART_ROOT, PROJECT_ROOT  # noqa: E402

GENERATOR_RELATIVE_PATH = "scripts/pipeline/10_generate_component_keys.py"
TARGET: Path = GENERATED_DART_ROOT / "component_keys.dart"

BASE_CLASS = "IComponent"
CLASS_PREFIX = "IComponent"
CLASS_SUFFIX = "Component"

_CLASS_RE = re.compile(
    r"^(?P<abstract>abstract\s+)?(?:final\s+|base\s+|sealed\s+)*class\s+"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s+extends\s+(?P<base>[A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)
_ABSTRACT_BASE_RE = re.compile(
    r"^abstract\s+(?:final\s+|base\s+|sealed\s+)*class\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)


def strip_affix(class_name: str) -> str:
    if class_name.startswith(CLASS_PREFIX) and len(class_name) > len(CLASS_PREFIX):
        stripped = class_name[len(CLASS_PREFIX):]
    elif class_name.endswith(CLASS_SUFFIX) and len(class_name) > len(CLASS_SUFFIX):
        stripped = class_name[: -len(CLASS_SUFFIX)]
    else:
        stripped = class_name
    return stripped[0].lower() + stripped[1:]


def collect_components() -> list[str]:
    """Concrete component class names, sorted — the extends chain resolved."""
    extends: dict[str, str] = {}
    abstract: set[str] = set()
    for path in sorted(COMPONENTS_ROOT.rglob("*.dart")):
        text = path.read_text(encoding="utf-8")
        for match in _CLASS_RE.finditer(text):
            extends[match.group("name")] = match.group("base")
            if match.group("abstract"):
                abstract.add(match.group("name"))
        for match in _ABSTRACT_BASE_RE.finditer(text):
            abstract.add(match.group("name"))

    def reaches_base(name: str) -> bool:
        seen: set[str] = set()
        cursor = name
        while cursor in extends and cursor not in seen:
            seen.add(cursor)
            cursor = extends[cursor]
            if cursor == BASE_CLASS:
                return True
        return False

    return sorted(
        name for name in extends
        if name not in abstract and name != BASE_CLASS and reaches_base(name)
    )


def render(components: list[str]) -> str:
    lines = [
        f"// AUTO-GENERATED by {GENERATOR_RELATIVE_PATH} — DO NOT EDIT (rule 17).",
        "// One constant per concrete component class under lib/src/core/components/;",
        "// the value is the class name, which IS the container key (rule 16).",
        "abstract final class ComponentKeys {",
    ]
    lines.extend(
        f"  static const String {strip_affix(name)} = '{name}';" for name in components
    )
    lines.append("}")
    return "\n".join(lines) + "\n"


def run(dry_run: bool = False, check: bool = False) -> int:
    components = collect_components()
    if not components:
        raise SystemExit("[10] no concrete components found — wrong tree?")
    content = render(components)

    if dry_run:
        print(content, end="")
        print(f"[10][dry-run] {len(components)} keys; nothing written.")
        return 0

    if check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != content:
            print(f"[10][check] {TARGET.relative_to(PROJECT_ROOT)} drifted from the "
                  f"component classes — run: .venv/bin/python dawnforge.py component-keys")
            return 1
        print(f"[10][check] {len(components)} keys match the SSOT.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"[10] wrote {len(components)} keys -> {TARGET.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sys.exit(run(dry_run=args.dry_run, check=args.check))
