// import 'package:dawnforge/gameplay/inventory/entities/enums/hand_item_id.dart';
// import 'package:dawnforge/gameplay/inventory/entities/enums/hand_item_quality.dart';
// import 'package:dawnforge/gameplay/inventory/entities/enums/loot_category.dart';
// import 'package:dawnforge/gameplay/inventory/entities/enums/season.dart';
// import 'package:dawnforge/gameplay/inventory/entities/data/item_icon_data.dart';
// import 'package:dawnforge/gameplay/inventory/items/harvest_loot_item.dart';

// final class ModernFarmHarvestLootItemDatabaseDef {
//   ModernFarmHarvestLootItemDatabaseDef._();
//   static const Map<HandItemId, HarvestLootItem> harvestLootItemList = {
//     HandItemId.carrot_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.carrot_loot_item,
//       name: 'Carrot',
//       description: 'A fresh orange carrot. Can be eaten or sold.',
//       quality: HandItemQuality.normal,
//       baseValue: 15,
//       healthRestore: 10,
//       staminaRestore: 10,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 1,
//         spriteColumnIndex: 12,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.strawberry_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.strawberry_loot_item,
//       name: 'Strawberry',
//       description: 'A fresh red strawberry. Can be eaten or sold.',
//       quality: HandItemQuality.normal,
//       baseValue: 15,
//       healthRestore: 10,
//       staminaRestore: 10,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 1,
//         spriteColumnIndex: 15,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.potato_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.potato_loot_item,
//       name: 'Potato',
//       description: 'A starchy potato. Can be cooked or sold.',
//       quality: HandItemQuality.normal,
//       baseValue: 12,
//       healthRestore: 15,
//       staminaRestore: 15,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 2,
//         spriteColumnIndex: 3,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.pumpkin_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.pumpkin_loot_item,
//       name: 'Pumpkin',
//       description: 'A large orange pumpkin. Great for cooking.',
//       quality: HandItemQuality.silver,
//       baseValue: 35,
//       healthRestore: 30,
//       staminaRestore: 30,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 1,
//         spriteColumnIndex: 2,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.turnip_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.turnip_loot_item,
//       name: 'Turnip',
//       description: 'A purple and white turnip. Nutritious vegetable.',
//       quality: HandItemQuality.normal,
//       baseValue: 10,
//       healthRestore: 8,
//       staminaRestore: 8,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 2,
//         spriteColumnIndex: 3,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.radish_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.radish_loot_item,
//       name: 'Radish',
//       description: 'A crisp radish. Can be eaten or sold.',
//       quality: HandItemQuality.normal,
//       baseValue: 12,
//       healthRestore: 8,
//       staminaRestore: 8,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 2,
//         spriteColumnIndex: 5,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.tomato_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.tomato_loot_item,
//       name: 'Tomato',
//       description: 'A juicy red tomato. Perfect for salads.',
//       quality: HandItemQuality.silver,
//       baseValue: 20,
//       healthRestore: 12,
//       staminaRestore: 12,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 1,
//         spriteColumnIndex: 1,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.corn_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.corn_loot_item,
//       name: 'Corn',
//       description: 'Sweet corn on the cob. Can be roasted.',
//       quality: HandItemQuality.silver,
//       baseValue: 18,
//       healthRestore: 14,
//       staminaRestore: 14,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 1,
//         spriteColumnIndex: 5,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.apple_loot_item: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.apple_loot_item,
//       name: 'Apple',
//       description: 'A crisp apple. Can be eaten or sold.',
//       quality: HandItemQuality.normal,
//       baseValue: 12,
//       healthRestore: 8,
//       staminaRestore: 8,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 2,
//         spriteColumnIndex: 5,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.apple: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.apple,
//       name: 'Apple',
//       description: 'Fresh apple you can eat or sell.',
//       quality: HandItemQuality.normal,
//       baseValue: 12,
//       healthRestore: 8,
//       staminaRestore: 8,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 1,
//         spriteColumnIndex: 16,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.strawberry: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.strawberry,
//       name: 'Strawberry',
//       description: 'Sweet strawberry ready to eat.',
//       quality: HandItemQuality.normal,
//       baseValue: 15,
//       healthRestore: 10,
//       staminaRestore: 10,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 1,
//         spriteColumnIndex: 15,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//     HandItemId.tomato: HarvestLootItem(
//       requiredSeason: SeasonType.any,
//       id: HandItemId.tomato,
//       name: 'Tomato',
//       description: 'Juicy tomato perfect for salads.',
//       quality: HandItemQuality.silver,
//       baseValue: 20,
//       healthRestore: 12,
//       staminaRestore: 12,
//       iconData: ItemIconData(
//         spritesheetPath: 'tiled/Modern_Farm_v1.2/Icons/Icons_16x16.png',
//         spriteWidth: 16,
//         spriteHeight: 16,
//         spriteRowIndex: 1,
//         spriteColumnIndex: 1,
//       ),
//       category: LootCategory.vegetable,
//       regrowthDays: 0,
//     ),
//   };
// }
